[package]
name = "neversink-filter-downloader"
version = "0.2.9"
authors = ["Dennis Hedegaard <dennis@dhedegaard.dk>"]
build = "build.rs"

[dependencies]
reqwest = "^0.6"
serde = "*"
serde_derive = "*"
serde_json = "*"
zip = "^0.2"
colored = "^1.5"
term-painter = "^0.2"
chrono = "^0.4"

[target.'cfg(windows)'.build-dependencies]
winres = "^0.1"

[package.metadata.winres]
OriginalFilename = "neversink-filter-downloader.exe"
ProductName = "NeverSink Lootfilter Downloader"