[package]
name = "neversink-filter-downloader"
version = "0.2.15"
authors = ["Dennis Hedegaard <dennis@dhedegaard.dk>"]
build = "build.rs"
edition = '2021'

[dependencies]
chrono = "^0.4"
colored = "^2.0"
dirs = "^4.0"
reqwest = { version = "0.11", features = ["json"] }
serde = "*"
serde_derive = "*"
serde_json = "*"
term-painter = "^0.3"
tokio = { version = "1", features = ["full"] }
zip = "^0.5"

[target.'cfg(windows)'.build-dependencies]
winres = "^0.1"

[package.metadata.winres]
OriginalFilename = "neversink-filter-downloader.exe"
ProductName = "NeverSink Lootfilter Downloader"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
