[package]
name = "neversink-filter-downloader"
version = "0.2.4"
authors = ["Dennis Hedegaard <dennis@dhedegaard.dk>"]
build = "build.rs"

[dependencies]
reqwest = "^0.8"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
zip = "^0.2"
colored = "^1.5"
term-painter = "^0.2"
chrono = "^0.4"

[build-dependencies]
winres = "^0.1"

[package.metadata.winres]
OriginalFilename = "neversink-filter-downloader.exe"
ProductName = "NeverSink Lootfilter Downloader"