[package]
name = "neversink-filter-downloader"
version = "0.2.15"
authors = ["Dennis Hedegaard <dennis@dhedegaard.dk>"]
build = "build.rs"
edition = '2021'

[dependencies]
reqwest = "^0.9.4"
serde = "*"
serde_derive = "*"
serde_json = "*"
zip = "^0.5"
colored = "^2.0"
term-painter = "^0.3"
chrono = "^0.4"
dirs = "^4.0"

[target.'cfg(windows)'.build-dependencies]
winres = "^0.1"

[package.metadata.winres]
OriginalFilename = "neversink-filter-downloader.exe"
ProductName = "NeverSink Lootfilter Downloader"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
