name: Release

# on:
#   push:
#     tags:
#       - "*"
on: [push]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest # windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Test the program
        run: cargo test

      - name: Build the program
        run: cargo build --release

      - name: Run the program
        run: cargo run --release -- -q

      - name: Copy release to release folder
        run: |
          bash -c "mkdir -p release"
          bash -c "cp -vf target/release/neversink-filter-downloader.exe ./release/."
          bash -c "cp -vf target/release/neversink-filter-downloader ./release/."

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: "release.zip"
          path: "./release"

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
